name: Deploy to Production

on:
    push:
        branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run composer install
      uses: php-actions/composer@v6
      with:
        dev: no
        args: --profile --ignore-platform-reqs

    - name: Explore the GitHub Workspace
    - run: ls
    - run: ls plugins
    - run: pwd

    - name: Deploy plugins to Flywheel
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: team+me+testing-composer-wpackagist-github-action
        SOURCE: plugins
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/

    - name: Deploy Theme to Flywheel
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ssh.getflywheel.com
        REMOTE_USER: team+me+testing-composer-wpackagist-github-action
        SOURCE: themes/neeon
        ARGS: -rltgoDzvO --exclude .git --exclude .github
        TARGET: /www/wp-content/themes/
